### ISSUE TITLE
Asset size when used via Browserify

### ISSUE THREAD

**Issue by jonjhiggins** [helpers/helper-md#1]
Hi 

Just started using this helper in a Browserify-based project, noticed the build file size jump up quite a bit when requiring helper-md.

I set up a test project that only includes helper-md and the built file came out at 937KB, which seems quite a lot. Most of that weight seems to come from its dependency on highlight.js (~600KB). I tried swapping it out for [highlight-redux](https://github.com/bevacqua/highlight-redux) which dropped it down to a more reasonable 310KB. 

I guess highlight.js is used for syntax highlighting, I haven't actually tested this out with helper-md, but thought I'd draw the file size to your attention and see if you had any ideas for reducing it?

Cheers
Jon

**Comment by jonschlinkert** [comment]
Hmm, maybe we should allow hightlight, or highlight-redux, to be passed on the options so we can remove the dep completely. thoughts? I'd take a pr if you want to give that a shot or whatever other ideas you have

**Comment by jonjhiggins** [comment]
Thanks for the swift reply Jon. 

Actually, now you say it I wonder if highlight / highlight-redux should be optional - as removing syntax highlighting drops the built (unminified) JS down to 41KB - so it's quite a big overhead for a feature I'm not using that much at the moment. 

Hopefully I'll get a chance to investigate making it optional and a PR in the near future

**Comment by jonschlinkert** [comment]
> I wonder if highlight / highlight-redux should be optional

yeah sorry that's exactly what I meant, agreed. 

> investigate making it optional

Actually I think all we need to do is remove [this code](https://github.com/helpers/helper-md/blob/master/index.js#L81-L94) from the options, and remove hilight.js from the deps. Then the user can just pass highlight in on the options.

**Comment by jonschlinkert** [comment]
closing since this was resovled by: https://github.com/helpers/helper-md/pull/2
